language: csharp
sudo: required 
dist: trusty
solution: FastBurgAlgorithmLibrary.sln
install:
  - nuget restore FastBurgAlgorithmLibrary.sln
script:
  - xbuild /p:Configuration=Release FastBurgAlgorithmLibrary.sln
  - mono ./packages/NUnit.Runners.*/tools/nunit-console.exe ./FastBurgAlgorithmLibraryUnitTests/bin/Release/FastBurgAlgorithmLibraryUnitTests.dll
