language: csharp
solution: FastBurgAlgorithmLibrary.sln
mono: none
dotnet: 2.1.3
script:
  - dotnet restore
  - dotnet build
  - dotnet test ./FastBurgAlgorithmLibraryUnitTests/bin/Release/FastBurgAlgorithmLibraryUnitTests.csproj

