language: csharp
solution: FastBurgAlgorithmLibrary.sln
install:
  - nuget restore FastBurgAlgorithmLibrary.sln
script:
  - xbuild /p:Configuration=Release FastBurgAlgorithmLibrary.sln
  - mono ./packages/NUnit.ConsoleRunner.*/tools/nunit3-console.exe ./FastBurgAlgorithmLibraryUnitTests/bin/Release/FastBurgAlgorithmLibraryUnitTests.dll
