language: csharp
solution: FastBurgAlgorithmLibrary.sln
mono: 5.2.0
dotnet: 2.0.0
install:
  - export FrameworkPathOverride=$(dirname $(which mono))/../lib/mono/4.5/
script:
  - dotnet restore
  - dotnet build
  - dotnet test ./FastBurgAlgorithmLibraryUnitTests/bin/Release/FastBurgAlgorithmLibraryUnitTests.csproj

