language: csharp
solution: FastBurgAlgorithmLibrary.sln
mono: none
dotnet: 1.1.5
script:
  - dotnet restore
  - dotnet build
  - dotnet test ./FastBurgAlgorithmLibraryUnitTests/bin/Release/FastBurgAlgorithmLibraryUnitTests.csproj

